---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Monolithic Stack'
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '192.168.0.0/16'
      Tags:
      - Key: Name
        Value: !Sub '${AWS::StackName}'
